# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "backbone" "1.3.3" "1.3.3" "0vvy9j5g88bjc588prv7l7d3x4bqgfphzynjvmxp68mq63a0x64y")
  (fetchbower "marionette" "3.5.1" "~3.x.x" "104wpvajagrsndxwmy0j8rvdcjnxf9f1x163lcyb20cqj0rh2vsb")
  (fetchbower "bootstrap" "3.3.7" "~3.3.7" "1fxdhmpfn6c6jfkp5wvbkj6caw0rz9235pbl0kkmds6s08c8m53m")
  (fetchbower "video.js" "4.11.4" "4.11.4" "1w0qmv99kqg8pj476kbx5d677x3f37wi1ggvjrii77wa8vnhzgm6")
  (fetchbower "videojs-youtube" "1.2.10" "1.2.10" "0sd4dl1j6k404xc3iamgmx3lxqadlsc1qv46m2176frka1l8c99p")
  (fetchbower "mousetrap" "1.6.2" "~1.6.0" "176sp1qlzi7crif6nn350bi9d4yvkd1zqx7p4p20gpryilxsy9hn")
  (fetchbower "font-awesome" "4.6.3" "~4.6.3" "1gvn83h3f8c9xpixpchslki86figc53m87gikj5281y6xgdvasn7")
  (fetchbower "underscore" "1.9.1" ">=1.8.0" "0qbapmwicr1i0wwal1q8q4i5qa6qzh147b9f86arf7jysm8zhzy6")
  (fetchbower "backbone.radio" "2.0.0" "^2.0.0" "1p9lhawh0z7x0ig66a90bsy8frywmwl4469f5znqjh9805pilbw0")
  (fetchbower "jquery" "3.3.1" "1.9.1 - 3" "0dglgy915l9fwzxg5b9v9fmrvminm8cv5cmpwi8y5mfnx4g7rcqi")
]; }
